steps:
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args:
      - gcloud
      - functions
      - deploy
      - message-bottle-bot
      - --entry-point=messageBottleBot
      - --gen2
      - --region=europe-west2
      - --runtime=nodejs16
      - --trigger-http
      - --set-env-vars=TELEGRAM_BOT_AUTHENTICATION_TOKEN=${_TELEGRAM_BOT_AUTHENTICATION_TOKEN}
      - --set-env-vars=PUBLIC_ENDPOINT=${_PUBLIC_ENDPOINT}
      - --set-env-vars=FIRESTORE_COLLECTION_NAME=${_FIRESTORE_COLLECTION_NAME}
      - --ingress-settings=all
      - --allow-unauthenticated
substitutions:
  _TELEGRAM_BOT_AUTHENTICATION_TOKEN: unused
  _PUBLIC_ENDPOINT: unused
  _FIRESTORE_COLLECTION_NAME: unused
